---
author:
  - 水滴
title: 'ggplot坐标轴的修改'
date: 2021-05-11
categories:
  - R
  - ggplot
  - 坐标轴
tags:
  - R
  - ggplot
  - 坐标轴
slug: ggplot_axis
weight: 0004
description: 使用R语言链接Mysql数据库进行数据查询
--- 

# 近期汇率走势

## 人民币汇率走势

<font face="思源宋体 CN" size=4>

```{r include=FALSE}
pacman::p_load(openxlsx,RODBC,RMySQL,RMariaDB,zeallot,readr,tidyverse)
con <- dbConnect(MariaDB(), host="", dbname="macroeconomics", user="root", password="Zh_xq1234@")
#查询数据库中的表
dbListTables(con)
#描述表格信息
dbGetQuery(con,"describe 人民币汇率（日）")
#简单查询
CNYUS<-dbGetQuery(con,"select 日期,`中间价:美元兑人民币` from 人民币汇率（日） order by 日期  desc")
CNYUS$日期<-as.Date(CNYUS$日期)
CNYUS<-CNYUS[1:900,]
```

```{r}
tail(CNYUS)
library(showtextdb)
library(sysfonts)
library(showtext)
library(ggthemes)
library(ggThemeAssist)
gg <- ggplot(CNYUS, aes(x = 日期, y = `中间价:美元兑人民币`))+
      geom_line()+
      scale_y_continuous(limits=c(6.25,7.25),expand=c(0,0))+
      scale_x_date(date_labels = "%m-%y",date_breaks = "2 month",expand=c(0,0))+
      labs(x = "日期", 
           y = "人民币对美元汇率中间价",
           title ="图1 人民币对美元汇率中间价",fill="");
gg <-gg+theme_stata()
```

```{r, fig.showtext=TRUE,fig.align="center"}
font_add("SourceHanSerifCN-Light", "SourceHanSerifCN-Light.otf")
gg <-gg+
  theme(plot.background = element_rect(fill = "antiquewhite",colour = NA, linetype = "solid"),
        plot.title = element_text(hjust = 0.5),
        text = element_text(size = 8,family="SourceHanSerifCN-Light"));
gg
```

## 美元汇率走势

```{r include=FALSE}
pacman::p_load(openxlsx,RODBC,RMySQL,RMariaDB,zeallot,readr,tidyverse)
con <- dbConnect(MariaDB(), host="", dbname="macroeconomics", user="root", password="Zh_xq1234@")
#查询数据库中的表
dbListTables(con)
#描述表格信息
dbGetQuery(con,"describe 人民币汇率（日）")
#简单查询
US_index<-dbGetQuery(con,"select * from 美元指数（日） order by 日期  desc")
US_index$日期<-as.Date(US_index$日期)
US_index<-US_index[1:900,]
```

```{r}
tail(US_index)
library(showtextdb)
library(sysfonts)
library(showtext)
library(ggthemes)
gg <- ggplot(US_index, aes(x = 日期, y = `美元指数`))+
      geom_line()+
      scale_y_continuous(limits=c(85,105),expand=c(0,0))+
      scale_x_date(date_labels = "%m-%y",date_breaks = "2 month",expand=c(0,0))+
      labs(x = "日期", 
           y = "美元汇率指数",
           title ="图2 美元汇率指数",fill="");
gg <-gg+theme_stata()
```


```{r, fig.showtext=TRUE,fig.align="center"}
font_add("SourceHanSerifCN-Light", "SourceHanSerifCN-Light.otf")
gg <-gg+
  theme(plot.background = element_rect(fill = "antiquewhite",colour = NA, linetype = "solid"),
        plot.title = element_text(hjust = 0.5),
        text = element_text(size = 8,family="SourceHanSerifCN-Light"));
gg
```


```{r}
CNYUS_US_index<-merge(CNYUS,US_index,by="日期")
colnames(CNYUS_US_index)<-c("date","Firm_stock_price","Index_price")
Firm_stock_price_Index_price<-CNYUS_US_index
head(Firm_stock_price_Index_price)
```

# 双坐标轴图

```{r, fig.showtext=TRUE}

Firm_stock_price_ceiling<-ceiling(range(Firm_stock_price_Index_price$Firm_stock_price)[2])
Firm_stock_price_floor<-floor(range(Firm_stock_price_Index_price$Firm_stock_price)[1])
Firm_stock_price_interval<-(Firm_stock_price_ceiling-Firm_stock_price_floor)/10

#指数数据
Index_ceiling<-ceiling(range(Firm_stock_price_Index_price$Index_price)[2])
Index_floor<-floor(range(Firm_stock_price_Index_price$Index_price)[1])
Index_interval<-(Index_ceiling-Index_floor)/10

#乘子
multiplicator<-Index_ceiling/Firm_stock_price_ceiling

font_add("SourceHanSerifCN-Light", "SourceHanSerifCN-Light.otf")
gg<-ggplot()+
  geom_line(data=Firm_stock_price_Index_price,aes(x=date,y=Firm_stock_price),stat="identity",size=0.5,color="red")+
  geom_line(data=Firm_stock_price_Index_price,aes(x=date,y=Index_price/multiplicator),size=0.5,color="blue")+
  scale_y_continuous(
    limits = c(Firm_stock_price_floor, Firm_stock_price_ceiling),
    breaks = c(seq(Firm_stock_price_floor,Firm_stock_price_ceiling,Firm_stock_price_interval)),
     label=seq(Firm_stock_price_floor,Firm_stock_price_ceiling,Firm_stock_price_interval),
     sec.axis=sec_axis(~./1,name="美元汇率指数（蓝色）",
          breaks =c(seq(Firm_stock_price_floor,Firm_stock_price_ceiling,Firm_stock_price_interval)),
          label=seq(round(Index_floor,2),Index_ceiling,Index_interval)) ,
    expand=c(0,0))+
  #设置X轴的标签
  scale_x_date(limits = c(Firm_stock_price_Index_price$date[1],Sys.Date()),date_labels = "%m-%y",date_breaks = "2 month",expand=c(0,0))+
  labs(x = "日期", 
       y = "人民币对美元汇率（红色）",
       title ="图3 人民币兑美元汇率 VS 人民币汇率指数",
       caption = "数据来源：iFind数据库。",
       tag = "这是附注",
       fill="")
gg <-gg+theme_stata()
```

```{r, fig.showtext=TRUE,fig.align="center"}
font_add("SourceHanSerifCN-Light", "SourceHanSerifCN-Light.otf")
gg <-gg+
  theme(plot.background = element_rect(fill = "antiquewhite",colour = NA, linetype = "solid"),
        plot.title = element_text(hjust = 0.5),
        plot.caption = element_text(hjust = 0,size = 8),
        plot.tag.position = "bottomright",
        text = element_text(size = 8,family="SourceHanSerifCN-Light"));
gg
```
