---
author:
  - 水滴
title: 'ggplot绘制条形图'
date: 2021-06-02
categories:
  - R
  - ggplot
  - 柱状图
tags:
  - R
  - ggplot
  - 柱状图
slug: ggplot
weight: 0004
description: ggolot绘图系列。
--- 

# 数据的获取  

```{r include=FALSE}
pacman::p_load(openxlsx,RODBC,RMySQL,RMariaDB,zeallot,readr,tidyverse,reshape2,ggthemes)
con <- dbConnect(MariaDB(), host="", dbname="macroeconomics", user="root", password="Zh_xq1234@")
```


```{r}
Mydata<-dbGetQuery(con,"select 日期,`出口总值:当月值`,`进口总值:当月值` from 进出口（月） order by 日期  desc")
Mydata$日期<-as.Date(Mydata$日期)
Mydata<-Mydata[1:5,]
colnames(Mydata)<-c("date","当月出口","当月进口")
Mydata<-melt(Mydata,id="date")
Mydata
```

# 绘制簇状条形图

```{r, fig.showtext=TRUE,fig.align="center"}
library(showtextdb)
library(sysfonts)
library(showtext)
library(ggthemes)
library(ggThemeAssist)
font_add("SourceHanSerifCN-Light", "SourceHanSerifCN-Light.otf")
gg<-ggplot(Mydata,aes(x = date,y = value,fill = variable))+
  geom_bar(stat = "identity", position = "dodge", width=25) +
  #identity表示条形的高度是变量值，"dodge"表示条形图并列，width表示柱子宽度，默认值是0.9
  scale_y_continuous(limit=c(0,3000),expand = c(0,0))+   # y轴起点从0开始
  scale_x_date(date_labels = "%Y-%m")+
  labs(title="2021年中国进出口",fill="图例" )+
  xlab("时间") + 
  ylab("进出口金额（亿美元）")+
  geom_text(aes(label = value), size= 2.5, color = "black", family = "SourceHanSerifCN-Light", position = position_dodge(20), vjust = -1)+   # 柱子添加文字数据标签
  theme_bw() +  # 移除背景
  theme_stata()+
  theme(plot.background = element_rect(fill = "antiquewhite",colour = NA, linetype = "solid"),
        plot.title = element_text(hjust = 0.5),
        text = element_text(family="SourceHanSerifCN-Light"),
        axis.text.x = element_text(size = 10, color = "black", face = "bold", family = "SourceHanSerifCN-Light"),
        axis.title.x = element_text(size = 10, color = "black", face = "bold", family = "SourceHanSerifCN-Light"),
        axis.text.y = element_text(size = 10, color = "black", face = "bold", family = "SourceHanSerifCN-Light"),
        axis.title.y = element_text(size = 10, color = "black", face = "bold", family = "SourceHanSerifCN-Light"),
        legend.title = element_text(size = 10,vjust = 0.5, color = "black", face = "bold", family = "SourceHanSerifCN-Light"),
        legend.text = element_text(size = 10, color = "black",face="bold", family="SourceHanSerifCN-Light"),
        legend.position="bottom",
        legend.background = element_blank(),
        legend.box = "horizontal")
gg
```


# 绘制堆叠条形图

```{r, fig.showtext=TRUE,fig.align="center"}
library(showtextdb)
library(sysfonts)
library(showtext)
library(ggthemes)
library(ggThemeAssist)
font_add("SourceHanSerifCN-Light", "SourceHanSerifCN-Light.otf")
gg<-ggplot(Mydata,aes(x = date,y = value,fill = variable))+
  geom_bar(stat = "identity", position =position_stack(reverse=T), width=20) +
  #identity表示条形的高度是变量值，"dodge"表示条形图并列，width表示柱子宽度，默认值是0.9
  scale_y_continuous(limit=c(0,5000),expand = c(0,0))+   # y轴起点从0开始
  scale_x_date(date_labels = "%Y-%m")+
  labs(title="2021年中国进出口",fill="图例" )+
  xlab("时间") + 
  ylab("进出口金额（亿美元）")+
  geom_text(aes(label = value), size= 2.5, color = "black", family = "SourceHanSerifCN-Light", position =  position_stack(0.5), vjust = -1)+   # 柱子添加文字数据标签
  theme(panel.grid=element_blank(),panel.border=element_blank(),axis.line=element_line(size=1,colour="black"))+# 去除网格线，添加坐标线
  theme_bw() +  # 移除背景
  theme_stata()+
  theme(plot.background = element_rect(fill = "antiquewhite",colour = NA, linetype = "solid"),
        plot.title = element_text(hjust = 0.5),
        text = element_text(family="SourceHanSerifCN-Light"),
        axis.text.x = element_text(size = 10, color = "black", face = "bold", family = "SourceHanSerifCN-Light"),
        axis.title.x = element_text(size = 10, color = "black", face = "bold", family = "SourceHanSerifCN-Light"),
        axis.text.y = element_text(size = 10, color = "black", face = "bold", family = "SourceHanSerifCN-Light"),
        axis.title.y = element_text(size = 10, color = "black", face = "bold", family = "SourceHanSerifCN-Light"),
        legend.title = element_text(size = 10,vjust = 0.5, color = "black", face = "bold", family = "SourceHanSerifCN-Light"),
        legend.text = element_text(size = 10, color = "black",face="bold", family="SourceHanSerifCN-Light"),
        legend.position="bottom",
        legend.background = element_blank(),
        legend.box = "horizontal")
gg
```






