---
author:
  - 水滴
title: 'R语言与数据库系列003：SQLite'
date: 2021-06-03
categories:
  - R
  - 数据库
  - 连接
  - SQLite
tags:
  - R
  - 数据库
  - 连接
  - SQLite
slug: SQLite
weight: 0004
description: RSQLite 可以在R中方便的创建sqlite数据库，并进行检索， 这个R包依赖于DBI包。
--- 

# RSQLite包的简要介绍

> R中连接数据库的包， 都依赖于DBI包, 除了RSQLite, 还有RMySQL, RPostgreSQL等连接其他数据库的包。

```{r}
pacman::p_load(DBI,RSQLite)
#创建一个临时内存的数据库
library(DBI)
# Create an ephemeral in-memory RSQLite database
con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbListTables(con)
```

```{r}
dbWriteTable(con, "mtcars", mtcars)
dbListTables(con)
```

```{r}
dbListFields(con, "mtcars")
```





# 时间日期型数据

## 获取当前日期


在MySQ中，其标准的语法结构都是：

```{sql, connection=con}
select current_date;
```

MySQL中日期型数据的显示格式：YYYY-MM-DD（四位数的年-月份-日期）

## 获取当前的系统时间  

在MySQ中，其标准的语法结构都是：

```{sql, connection=con}
select current_time;
```  


## 获取当前系统日期与时间  

```{sql, connection=con}
select current_timestamp;
```

```{r}
dbDisconnect(con) # 断开连接
```


# SQL数据查询之跨表查询


```{r include=FALSE}
pacman::p_load(RMySQL,RMariaDB,zeallot)
con <- dbConnect(MariaDB(), host="", dbname="learning", user="root", password="Zh_xq1234@")#,host="127.0.0.1", port=3306
```


```{r}
person<-dbGetQuery(con, "SELECT * FROM person")  
person
```

```{r}
dept<-dbGetQuery(con,"select * from dept")
dept
```


```{r}
pacman::p_load(DBI,RSQLite)
#创建一个临时内存的数据库
library(DBI)
# Create an ephemeral in-memory RSQLite database
con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbListTables(con)
```

```{r}
dbWriteTable(con, "person",person)
dbListTables(con)
```

```{r}
dbWriteTable(con, "dept",dept)
dbListTables(con)
```


```{sql, connection=con,, max.print = 20}
select * from person
```

```{sql, connection=con,, max.print = 20}
select * from person
```

```{sql, connection=con,max.print = 100}
select * from person,dept
```

```{sql, connection=con,max.print = 100}
select * from person,dept where person.id = dept.did
```


```{sql, connection=con,max.print = 100}
select * from person inner join dept  on person.id =dept.did;
```
