---
author:
  - 通达信公式
title: '通达信公式'
categories:
  - 通达信
  - 选股策略
tags:
  - 通达信
  - 选股策略
date: 2021-12-30
slug: TDX
weight: 001
description: <font face="思源宋体 CN" >通达信公式研究系列</font>
---

<font face="思源宋体 CN" >

# 关键概念

## 公式编辑器

“ 公式编辑器 ” 好比是一个工作母床，通过这个工作母床可以制造出所需要的各式各样的零件，同样，在指标分析的工作中，利用编辑器可以编写出相应的分析条件，这种方法是在技术分析当中最为常用的方法之一。例如，指标 KD 、指标 MA 等等，通过对这些指标的观察、分析，找出一些合适的条件作为买入卖出点。当然，我们也许需要的是一些自己的指标，一些自己的准确的指标，更多的 MB 、 MC 、 MD 等等，这一切我们通过 “ 公式编辑器 ” 可以实现。

## 条件选股

编写公式都要用到什么东西？
我们留下了许多问题 -- 都是公式编写的基础问题，所以我们这节课来解决这些基础的问题。
什么是技术指标？
MA 均线就是一种技术指标，我们在炒股的时候，经常会将一些行情数据进行数学计算得出一些曲线等等，方便我们掌握股市的变动情况。
什么是条件选股？
简单讲，就是按照您的设定的条件用电脑帮助您完成一些太多太复杂的挑选 -- 比如您有一些好的心得和方法，可使有 1000 多只股票，您就是有 100 双眼睛有时也不一定可以看得过来，这时电脑就派上用场了！
什么是参数？
比如讲： 10 日均线，您可以把 10 日当作参数，好处在于，您觉得需要修改成 5 日的时候，就可以使用一些简单的方法，例如参数精灵来很方便的修改和调整。参数需要名字，例如 M 就不错。还要规定参数的范围，例如 1 日至 260 日。这样我们就可以在 1 到 260 之间任意调节 M 的值了， M 最常用的数填在 “ 缺省 ” 一栏，例如你最喜欢用 10 日均线，那就填 10 吧。

## 周期

这么解释吧！我们有的投资者喜欢使用日线图作技术分析；有的喜欢用 5 分钟的 K 线；有的喜欢使用长一点时间的，例如周线。所以在公式设计中，允许不同喜好的使用者选择不同的分析时间 -- 就是可以选择不同的周期。

## 函数

函数在公式编写非常重要，如果作个比喻，我们用一种语言去告诉电脑我的想法，并且让它去帮我做，那么函数就是这种语言的单词。
我们在公式编辑器中选择插入函数，就可以看到里面有许多的函数，我们在附录中有一个简表，大家可以到那里去检索！

## 几个简单的例子

###  例一：一根 K 线有四个价格组成

最高价： HIGH
收盘价： CLOSE
最低价： LOW
开盘价： OPEN
成交量： VOL
成交额： AMO

### 例二：两条均线不断地交叉，就专门设定了一条函数来描述两条线交叉

```
CROSS （ X ， Y ）
```
假如下图中的两条均线一条名叫 X ，另外一条叫 Y
`CROSS （ X ， Y ）`表示 X 向上穿过了 Y
CROSS `（ Y ， X ）`表示 Y 向上穿过了 X

### 例三：周K线

前面的 CLOSE ，还是 VOL ，都表示当天，或者您使用的不是日线，那就表示本周期的数据，那么前几天的怎么表示呢？
REF （ X ， M ）
例如：
`REF （ Close ， 5 ）`表示 5 天前的收盘；
`REF （ Vol ， 10 ）`表示 10 天前的成交量；
这里的 M 就是参数，您现在明白了什么是参数了吗？
### 例四：如果我想把两个条件并列在一起怎么办？

`AND`。
`X AND Y `就表示条件 X 和条件 Y


### 注意事项  


- 1 、如果选择： “ 主图叠加 ” ，我们的指标线会与 K 线图显示在同一个图形框中，现在我们的指标线显示在其下方，即 “ 副图 ” 中；
- 2 、参数可以有，也可以没有，但是鼓励大家设置参数，这是非常好的习惯；
- 3 、一个句子完了，别忘了以分号结尾；
你的公式写得对不对，可以通过 “ 测试公式 ” 来检查，如果错了，它会告诉你错在哪里。

### 条件选股总结  

1 、指标和条件选股在结构上没有差别，只是在内容上，条件选股要多加上我们的条件，比如大于 10 ，或者交叉等等！

2 、中间表达式可以帮助我们清晰的表达我们的公式，不至于使公式的结构特别的混乱！


##　画线指标公式编辑器

- ［公式名称］用于识别指标公式，不能重名，最多可以有16个字符。键盘精灵也用该名称来选择公式。
- ［公式描述］简单描述该指标的用途。
- ［密码保护］如果其前未打√，表示该公式没加密。点击"密码保护"，使其打√选中，此时输入密码，公式就被加密。对于已加密的公式，必须输入密码才能看到公式的内容，要去掉密码，点击"密码保护"，使它前面的√消失即可。
- ［指标类型］指定指标公式类型（共分为15种）。
- ［画线方法］紧密围绕股票价格变化的指标可定为主图叠加类型，叠加在主图上显示；否则定为副图指标，只能显示在副图上。
- ［参数名称］公式可以带参数，参数的名字在这里输入。
- ［最小值、最大值、缺省值］参数的最小值、最大值和默认值（缺省值）在这里输入。
- ［坐标线位置］仅对副图指标有效，可指定在哪些位置画水平坐标线，例如对BIAS，可以输入：-20；0；20； 系统将在这三个数值处绘制三条水平坐标线。缺省时为"自动"，即系统据实际情况定水平坐标线。
- ［额外Y轴分界］
- ［引入指标公式］以系统已有的某个指标公式为蓝本，新建自己的指标公式。
- ［插入函数］显示选择函数对话框，帮助您在《通达信集成版》软件函数集中寻找所需函数。当您对系统提供的标准函数还不熟时，这个功能可帮你节省时间。

- 　Tdxw3.0将函数类型分为：
全部函数 行情函数 时间函数 引用函数 逻辑函数
数学函数 统计函数 指数函数 大盘函数 常数函数
内嵌函数 操作符函数
- 　[动态提示]用户输入指标、算法或函数时，同步提示中文语意。
- [测试公式]公式编写完毕后检查公式的语法错误。
- [测试结果]测试完毕后提示"测试通过"或显示错误信息。
- [参数精灵]用户新建公式时，可在参数精灵中用一段文字来描述待设置参数的意义，这段解释性文字会在允许用户调整参数值的地方出现，包括条件选股、指标排序、调整指标参数、选择指标、选择交易系统指示、选择条件选股指示等等。有了这段解释性文字的指导，用户就不会盲目操作了。

## 条件选股公式编辑器

条件选股公式编辑器与指标公式编辑器极为相似，因此不专门讲解它。

##　交易系统公式编辑器

在新建、修改交易系统公式时，将弹出交易系统公式编辑器对话框。
比较指标公式编辑器我们只对多出的部分进行讲解。
［测试步长］在进行参数优化时，每次参数变化的大小。
［多头买入］做多时的买入条件在此输入，买入点指示的颜色及式样也请在此选定。
［多头卖出］　做多时的卖出条件在此输入，卖出点指示的颜色及式样也请在此选定。
［空头买入］　做空时的买入条件在此输入，买入点指示的颜色及式样也请在此选定。
［空头卖出］做空时的卖出条件在此输入，卖出点指示的颜色及式样也请在此选定。

##　五彩K线公式编辑器
　　 与指标公式编辑器的使用相似

# 选股公式

# 指标公式
